
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
  
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: 
      paths:
        - path: /
          pathType: ImplementationSpecific
  

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
