apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      run: demo
  replicas: 1
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: demo:1
        ports:
        - containerPort: 8080